version: "3.8"

services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist PostgreSQL data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db

  api:
    container_name: api
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "poetry",
        "run",
        "uvicorn",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "main:api",
        "--reload",
      ]
    volumes:
      - .:/EduInsights
      - /EduInsights/.venv
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

  redis:
    container_name: redis
    image: redis:alpine

  celery_worker:
    container_name: celery_worker
    image: celery_worker_edu
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "poetry",
        "run",
        "celery",
        "-A",
        "celery_worker.celery",
        "worker",
        "--loglevel=info",
      ]
    volumes:
      - .:/EduInsights
      - /EduInsights/.venv
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - db
      - redis
    restart: always

  flower:
    container_name: flower
    image: flower_edu
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "poetry",
        "run",
        "celery",
        "-A",
        "celery_worker.celery",
        "flower",
        "--port=5555",
      ]
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - db
      - redis
      - celery_worker
    restart: always

volumes:
  postgres_data: # Named volume for PostgreSQL data persistence
