"""added start&end usn

Revision ID: 1faaeaf8c38f
Revises: 9428242966fb
Create Date: 2024-05-17 06:21:12.471954

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1faaeaf8c38f"
down_revision: Union[str, None] = "9428242966fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "batches", sa.Column("start_usn", sa.String(length=10), nullable=True)
    )
    op.add_column("batches", sa.Column("end_usn", sa.String(length=10), nullable=True))
    op.add_column(
        "sections", sa.Column("start_usn", sa.String(length=10), nullable=True)
    )
    op.add_column("sections", sa.Column("end_usn", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sections", "end_usn")
    op.drop_column("sections", "start_usn")
    op.drop_column("batches", "end_usn")
    op.drop_column("batches", "start_usn")
    # ### end Alembic commands ###
