"""empty message

Revision ID: 27c2b08c0a31
Revises: 9e280a8534e6
Create Date: 2024-05-19 20:21:50.849869

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27c2b08c0a31"
down_revision: Union[str, None] = "9e280a8534e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("extractions", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("extractions", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("extractions", "updated_at")
    op.drop_column("extractions", "created_at")
    # ### end Alembic commands ###
