"""added lateral start&end usn

Revision ID: 294592dae1e8
Revises: 1faaeaf8c38f
Create Date: 2024-05-17 06:36:37.100134

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "294592dae1e8"
down_revision: Union[str, None] = "1faaeaf8c38f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "batches", sa.Column("lateral_start_usn", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "batches", sa.Column("lateral_end_usn", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "sections", sa.Column("lateral_start_usn", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "sections", sa.Column("lateral_end_usn", sa.String(length=10), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sections", "lateral_end_usn")
    op.drop_column("sections", "lateral_start_usn")
    op.drop_column("batches", "lateral_end_usn")
    op.drop_column("batches", "lateral_start_usn")
    # ### end Alembic commands ###
