"""Removed enum Depts

Revision ID: 40deb130cb9a
Revises: 9f369a331f1c
Create Date: 2024-05-15 19:58:57.521568

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40deb130cb9a"
down_revision: Union[str, None] = "9f369a331f1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "departments",
        "dept_name",
        existing_type=postgresql.ENUM(
            "CSE", "ISE", "AIML", "ECE", "EEE", "MECH", "CIVIL", name="depts"
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "departments",
        "dept_name",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "CSE", "ISE", "AIML", "ECE", "EEE", "MECH", "CIVIL", name="depts"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
