"""empty message

Revision ID: 6fe9a8f558bd
Revises: e6020ad54446
Create Date: 2024-05-17 18:55:49.240096

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fe9a8f558bd"
down_revision: Union[str, None] = "e6020ad54446"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("batches_dept_id_fkey", "batches", type_="foreignkey")
    op.create_foreign_key(None, "batches", "departments", ["dept_id"], ["dept_id"])
    op.drop_constraint("marks_stud_id_fkey", "marks", type_="foreignkey")
    op.drop_constraint("marks_subject_id_fkey", "marks", type_="foreignkey")
    op.drop_constraint("marks_section_id_fkey", "marks", type_="foreignkey")
    op.create_foreign_key(None, "marks", "sections", ["section_id"], ["section_id"])
    op.create_foreign_key(None, "marks", "students", ["stud_id"], ["stud_id"])
    op.create_foreign_key(None, "marks", "subjects", ["subject_id"], ["subject_id"])
    op.alter_column("semesters", "current", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_constraint("semesters_batch_id_fkey", "semesters", type_="foreignkey")
    op.create_foreign_key(None, "semesters", "batches", ["batch_id"], ["batch_id"])
    op.drop_constraint("check_usn_unique", "students", type_="unique")
    op.drop_constraint("students_current_sem_fkey", "students", type_="foreignkey")
    op.drop_constraint("students_batch_id_fkey", "students", type_="foreignkey")
    op.drop_constraint("students_section_id_fkey", "students", type_="foreignkey")
    op.create_foreign_key(None, "students", "batches", ["batch_id"], ["batch_id"])
    op.create_foreign_key(None, "students", "sections", ["section_id"], ["section_id"])
    op.create_foreign_key(None, "students", "semesters", ["current_sem"], ["sem_id"])
    op.drop_constraint("subjects_sem_id_fkey", "subjects", type_="foreignkey")
    op.create_foreign_key(None, "subjects", "semesters", ["sem_id"], ["sem_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subjects", type_="foreignkey")
    op.create_foreign_key(
        "subjects_sem_id_fkey",
        "subjects",
        "semesters",
        ["sem_id"],
        ["sem_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "students", type_="foreignkey")
    op.drop_constraint(None, "students", type_="foreignkey")
    op.drop_constraint(None, "students", type_="foreignkey")
    op.create_foreign_key(
        "students_section_id_fkey",
        "students",
        "sections",
        ["section_id"],
        ["section_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "students_batch_id_fkey",
        "students",
        "batches",
        ["batch_id"],
        ["batch_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "students_current_sem_fkey",
        "students",
        "semesters",
        ["current_sem"],
        ["sem_id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint("check_usn_unique", "students", ["usn"])
    op.drop_constraint(None, "semesters", type_="foreignkey")
    op.create_foreign_key(
        "semesters_batch_id_fkey",
        "semesters",
        "batches",
        ["batch_id"],
        ["batch_id"],
        ondelete="CASCADE",
    )
    op.alter_column("semesters", "current", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_constraint(None, "marks", type_="foreignkey")
    op.drop_constraint(None, "marks", type_="foreignkey")
    op.drop_constraint(None, "marks", type_="foreignkey")
    op.create_foreign_key(
        "marks_section_id_fkey",
        "marks",
        "sections",
        ["section_id"],
        ["section_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "marks_subject_id_fkey",
        "marks",
        "subjects",
        ["subject_id"],
        ["subject_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "marks_stud_id_fkey",
        "marks",
        "students",
        ["stud_id"],
        ["stud_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "batches", type_="foreignkey")
    op.create_foreign_key(
        "batches_dept_id_fkey",
        "batches",
        "departments",
        ["dept_id"],
        ["dept_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
