"""empty message

Revision ID: 7d35fdd8457e
Revises: 6fe9a8f558bd
Create Date: 2024-05-17 19:35:28.245293

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d35fdd8457e"
down_revision: Union[str, None] = "6fe9a8f558bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("students_batch_id_fkey", "students", type_="foreignkey")
    op.create_foreign_key(
        None, "students", "batches", ["batch_id"], ["batch_id"], ondelete="CASCADE"
    )
    op.drop_constraint("subjects_sem_id_fkey", "subjects", type_="foreignkey")
    op.create_foreign_key(None, "subjects", "semesters", ["sem_id"], ["sem_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subjects", type_="foreignkey")
    op.create_foreign_key(
        "subjects_sem_id_fkey",
        "subjects",
        "semesters",
        ["sem_id"],
        ["sem_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "students", type_="foreignkey")
    op.create_foreign_key(
        "students_batch_id_fkey", "students", "batches", ["batch_id"], ["batch_id"]
    )
    # ### end Alembic commands ###
