"""Removed enum section

Revision ID: 7f19f6cfb740
Revises: 40deb130cb9a
Create Date: 2024-05-15 20:07:33.894695

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f19f6cfb740"
down_revision: Union[str, None] = "40deb130cb9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sections",
        "section",
        existing_type=postgresql.ENUM("A", "B", "C", "D", "E", name="sectionname"),
        type_=sa.String(length=1),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sections",
        "section",
        existing_type=sa.String(length=1),
        type_=postgresql.ENUM("A", "B", "C", "D", "E", name="sectionname"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
