"""Splitted batch_year attr

Revision ID: 9428242966fb
Revises: c71d8e8771d6
Create Date: 2024-05-16 21:18:01.183728

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9428242966fb"
down_revision: Union[str, None] = "c71d8e8771d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("batches", sa.Column("batch_start_year", sa.Integer(), nullable=True))
    op.add_column("batches", sa.Column("batch_end_year", sa.Integer(), nullable=True))
    op.drop_index("ix_batches_batch_year", table_name="batches")
    op.create_index(
        op.f("ix_batches_batch_end_year"), "batches", ["batch_end_year"], unique=False
    )
    op.create_index(
        op.f("ix_batches_batch_start_year"),
        "batches",
        ["batch_start_year"],
        unique=False,
    )
    op.drop_column("batches", "batch_year")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "batches",
        sa.Column(
            "batch_year", sa.VARCHAR(length=9), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_batches_batch_start_year"), table_name="batches")
    op.drop_index(op.f("ix_batches_batch_end_year"), table_name="batches")
    op.create_index("ix_batches_batch_year", "batches", ["batch_year"], unique=False)
    op.drop_column("batches", "batch_end_year")
    op.drop_column("batches", "batch_start_year")
    # ### end Alembic commands ###
