"""cgpa(2,2)->cgpa(3,1)

Revision ID: 9c23bc48cbc0
Revises: 7f19f6cfb740
Create Date: 2024-05-15 23:04:54.598142

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c23bc48cbc0"
down_revision: Union[str, None] = "7f19f6cfb740"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students",
        "cgpa",
        existing_type=sa.NUMERIC(precision=2, scale=2),
        type_=sa.Numeric(precision=3, scale=1),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students",
        "cgpa",
        existing_type=sa.Numeric(precision=3, scale=1),
        type_=sa.NUMERIC(precision=2, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
