"""added extractions table

Revision ID: 9e280a8534e6
Revises: d4825a55c416
Create Date: 2024-05-19 20:19:51.657016

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e280a8534e6"
down_revision: Union[str, None] = "d4825a55c416"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extractions",
        sa.Column("extraction_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("sem_id", sa.Integer(), nullable=False),
        sa.Column("total_usns", sa.Integer(), nullable=False),
        sa.Column("num_completed", sa.Integer(), nullable=False),
        sa.Column("num_invalid", sa.Integer(), nullable=False),
        sa.Column("reattempts", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("failed", sa.Boolean(), nullable=False),
        sa.Column("time_taken", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["section_id"], ["sections.section_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["sem_id"], ["semesters.sem_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("extraction_id"),
    )
    op.create_index(
        op.f("ix_extractions_extraction_id"),
        "extractions",
        ["extraction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extractions_num_completed"),
        "extractions",
        ["num_completed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extractions_num_invalid"), "extractions", ["num_invalid"], unique=False
    )
    op.create_index(
        op.f("ix_extractions_progress"), "extractions", ["progress"], unique=False
    )
    op.create_index(
        op.f("ix_extractions_reattempts"), "extractions", ["reattempts"], unique=False
    )
    op.create_index(
        op.f("ix_extractions_time_taken"), "extractions", ["time_taken"], unique=False
    )
    op.create_index(
        op.f("ix_extractions_total_usns"), "extractions", ["total_usns"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_extractions_total_usns"), table_name="extractions")
    op.drop_index(op.f("ix_extractions_time_taken"), table_name="extractions")
    op.drop_index(op.f("ix_extractions_reattempts"), table_name="extractions")
    op.drop_index(op.f("ix_extractions_progress"), table_name="extractions")
    op.drop_index(op.f("ix_extractions_num_invalid"), table_name="extractions")
    op.drop_index(op.f("ix_extractions_num_completed"), table_name="extractions")
    op.drop_index(op.f("ix_extractions_extraction_id"), table_name="extractions")
    op.drop_table("extractions")
    # ### end Alembic commands ###
