"""added extraction_invalid table

Revision ID: b77dba5e801f
Revises: 27c2b08c0a31
Create Date: 2024-05-29 16:18:23.909248

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b77dba5e801f"
down_revision: Union[str, None] = "27c2b08c0a31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extraction_invalids",
        sa.Column("invalid_id", sa.Integer(), nullable=False),
        sa.Column("extraction_id", sa.Integer(), nullable=False),
        sa.Column("invalid_usns", sa.String(), nullable=True),
        sa.Column("captcha_usns", sa.String(), nullable=True),
        sa.Column("timeout_usns", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["extraction_id"], ["extractions.extraction_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("invalid_id"),
    )
    op.create_index(
        op.f("ix_extraction_invalids_invalid_id"),
        "extraction_invalids",
        ["invalid_id"],
        unique=False,
    )
    op.add_column("extractions", sa.Column("num_captcha", sa.Integer(), nullable=False))
    op.add_column("extractions", sa.Column("num_timeout", sa.Integer(), nullable=False))
    op.create_index(
        op.f("ix_extractions_num_captcha"), "extractions", ["num_captcha"], unique=False
    )
    op.create_index(
        op.f("ix_extractions_num_timeout"), "extractions", ["num_timeout"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_extractions_num_timeout"), table_name="extractions")
    op.drop_index(op.f("ix_extractions_num_captcha"), table_name="extractions")
    op.drop_column("extractions", "num_timeout")
    op.drop_column("extractions", "num_captcha")
    op.drop_index(
        op.f("ix_extraction_invalids_invalid_id"), table_name="extraction_invalids"
    )
    op.drop_table("extraction_invalids")
    # ### end Alembic commands ###
