"""removed enum marks

Revision ID: c71d8e8771d6
Revises: 9c23bc48cbc0
Create Date: 2024-05-15 23:22:31.311437

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c71d8e8771d6"
down_revision: Union[str, None] = "9c23bc48cbc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "marks",
        "result",
        existing_type=postgresql.ENUM("F", "P", "W", name="results"),
        type_=sa.String(length=1),
        existing_nullable=False,
    )
    op.alter_column(
        "marks",
        "grade",
        existing_type=postgresql.ENUM(
            "FCD", "FC", "SC", "FAIL", "ABSENT", name="grades"
        ),
        type_=sa.String(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "marks",
        "grade",
        existing_type=sa.String(length=10),
        type_=postgresql.ENUM("FCD", "FC", "SC", "FAIL", "ABSENT", name="grades"),
        existing_nullable=False,
    )
    op.alter_column(
        "marks",
        "result",
        existing_type=sa.String(length=1),
        type_=postgresql.ENUM("F", "P", "W", name="results"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
