"""added student_performances table

Revision ID: d4825a55c416
Revises: 20e1c8fcbde7
Create Date: 2024-05-17 20:35:38.096580

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4825a55c416"
down_revision: Union[str, None] = "20e1c8fcbde7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_performances",
        sa.Column("stud_perf_id", sa.Integer(), nullable=False),
        sa.Column("stud_id", sa.Integer(), nullable=False),
        sa.Column("sem_id", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("percentage", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("sgpa", sa.Numeric(precision=3, scale=1), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["sem_id"], ["semesters.sem_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stud_id"], ["students.stud_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("stud_perf_id"),
    )
    op.create_index(
        op.f("ix_student_performances_percentage"),
        "student_performances",
        ["percentage"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_performances_sgpa"),
        "student_performances",
        ["sgpa"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_performances_stud_perf_id"),
        "student_performances",
        ["stud_perf_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_performances_total"),
        "student_performances",
        ["total"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_student_performances_total"), table_name="student_performances"
    )
    op.drop_index(
        op.f("ix_student_performances_stud_perf_id"), table_name="student_performances"
    )
    op.drop_index(
        op.f("ix_student_performances_sgpa"), table_name="student_performances"
    )
    op.drop_index(
        op.f("ix_student_performances_percentage"), table_name="student_performances"
    )
    op.drop_table("student_performances")
    # ### end Alembic commands ###
