"""added current to semester

Revision ID: e6020ad54446
Revises: 612f5a4c37b3
Create Date: 2024-05-17 07:34:56.745733

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6020ad54446"
down_revision: Union[str, None] = "612f5a4c37b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("semesters", sa.Column("current", sa.Boolean(), nullable=True))
    op.create_index(
        op.f("ix_semesters_current"), "semesters", ["current"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_semesters_current"), table_name="semesters")
    op.drop_column("semesters", "current")
    # ### end Alembic commands ###
