"""added on delete cascades

Revision ID: e786d4650f75
Revises: 7d35fdd8457e
Create Date: 2024-05-17 19:47:44.247691

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e786d4650f75"
down_revision: Union[str, None] = "7d35fdd8457e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("batches_dept_id_fkey", "batches", type_="foreignkey")
    op.create_foreign_key(
        None, "batches", "departments", ["dept_id"], ["dept_id"], ondelete="CASCADE"
    )
    op.drop_constraint("marks_stud_id_fkey", "marks", type_="foreignkey")
    op.drop_constraint("marks_subject_id_fkey", "marks", type_="foreignkey")
    op.drop_constraint("marks_section_id_fkey", "marks", type_="foreignkey")
    op.create_foreign_key(
        None, "marks", "students", ["stud_id"], ["stud_id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "marks", "sections", ["section_id"], ["section_id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "marks", "subjects", ["subject_id"], ["subject_id"], ondelete="CASCADE"
    )
    op.drop_constraint("students_current_sem_fkey", "students", type_="foreignkey")
    op.drop_constraint("students_section_id_fkey", "students", type_="foreignkey")
    op.create_foreign_key(
        None, "students", "semesters", ["current_sem"], ["sem_id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "students", "sections", ["section_id"], ["section_id"], ondelete="CASCADE"
    )
    op.drop_constraint("subjects_sem_id_fkey", "subjects", type_="foreignkey")
    op.create_foreign_key(
        None, "subjects", "semesters", ["sem_id"], ["sem_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subjects", type_="foreignkey")
    op.create_foreign_key(
        "subjects_sem_id_fkey", "subjects", "semesters", ["sem_id"], ["sem_id"]
    )
    op.drop_constraint(None, "students", type_="foreignkey")
    op.drop_constraint(None, "students", type_="foreignkey")
    op.create_foreign_key(
        "students_section_id_fkey",
        "students",
        "sections",
        ["section_id"],
        ["section_id"],
    )
    op.create_foreign_key(
        "students_current_sem_fkey",
        "students",
        "semesters",
        ["current_sem"],
        ["sem_id"],
    )
    op.drop_constraint(None, "marks", type_="foreignkey")
    op.drop_constraint(None, "marks", type_="foreignkey")
    op.drop_constraint(None, "marks", type_="foreignkey")
    op.create_foreign_key(
        "marks_section_id_fkey", "marks", "sections", ["section_id"], ["section_id"]
    )
    op.create_foreign_key(
        "marks_subject_id_fkey", "marks", "subjects", ["subject_id"], ["subject_id"]
    )
    op.create_foreign_key(
        "marks_stud_id_fkey", "marks", "students", ["stud_id"], ["stud_id"]
    )
    op.drop_constraint(None, "batches", type_="foreignkey")
    op.create_foreign_key(
        "batches_dept_id_fkey", "batches", "departments", ["dept_id"], ["dept_id"]
    )
    # ### end Alembic commands ###
